ktor:
  application:
    modules:
      - com.japp.ApplicationKt.module
  deployment:
    port: 8080

postgres:
  url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/japp}
  user: ${POSTGRES_USER:japp}
  password: ${POSTGRES_PASS:japper}