ktor {
    deployment {
        port = 3000
        port = ${?PORT}
    }
    application {
        modules = [ com.japp.ApplicationKt.module ]
    }
}

database {
    host = "localhost"
    host = ${?DB_HOST}
    port = 5432
    port = ${?DB_PORT}
    name = "japp"
    name = ${?DB_NAME}
    user = "japp_user"
    user = ${?DB_USER}
    password = ${?DB_PASSWORD}
}

jwt {
    secret = ${?JWT_SECRET}
    issuer = "japp-issuer"
    audience = "japp-audience"
}

upload {
    maxFileSize = 5242880
    profilesDir = "uploads/profiles"
    receiptsDir = "uploads/receipts"
}